### ISSUE TITLE
Support underline syntax in AbstractMark 

### ISSUE THREAD

**Issue by kimlimjustin** [abstractmark/abstractmark#1]
Hello, everyone. I have an idea about supporting underline syntax in AbstractMark which is not supported in markdown language. Any ideas about the syntax for underline? My proposal is to use % as the syntax(for example: %text%),any thoughts?

**Comment by stanleyowen** [comment]
Hi @kimlimjustin, thanks for your suggestion. I think it will be a good idea to support Underline styling in AbstractMark using %text%, I will list that in the Documentation soon!

**Comment by kimlimjustin** [comment]
thanks @stanleyowen

**Comment by stanleyowen** [comment]
Hi @kimlimjustin, I have updated the docs, you can visit them here: [https://github.com/abstractmark/abstractmark/blob/master/README.md]. Let me know if you have any suggestions again and we will happy to hear your suggestion :)
